### ISSUE TITLE
select multiple at once?

### ISSUE THREAD

**Issue by niftylettuce** [rhaker/react-native-select-contact-android#1]
same for your ios package, can we get a checkbox-like thing where we can select multiple contacts?

**Comment by rhaker** [comment]
Hi there. thanks for trying out the modules.

For what you are trying to do, you may want to consider the following: 

1) use the react-native-contacts module to pull in all the contacts
2) cache or store these contacts locally on initial mount
3) use javascript to display the contacts as some sort of dropdown select list (where multiple options can be selected). you can style and arrange this list as you see fit.

All the best.
