### ISSUE TITLE
Selecting multiple contacts

### ISSUE THREAD

**Issue by abeikverdi** [rhaker/react-native-select-contact-android#5]
Is it possible to select multiple contacts at the same time using this library?

**Comment by rhaker** [comment]
Thanks for the question. I don't think you can select multiple contacts at once. After you tap a contact, the data is invoked and captured in javascript. So you'd have to build a loop to capture each contact one at a time.

**Comment by abeikverdi** [comment]
How would that look from the user's perspective? It would I guess create a little disruption between each contact selection, right?

**Comment by rhaker** [comment]
It's certainly not ideal. The ideal case would be to have a list that you could check off to select the contacts of interest. If you want to try to implement that, feel free to do a pull request and I'll take a look at it.

**Comment by abeikverdi** [comment]
Alright sure.

**Comment by rhaker** [comment]
@lwhiteley just pushed an update that handles multiple emails and phone numbers.

**Comment by lwhiteley** [comment]
yea was about to say this seems like a different issue. my PR adds multiple numbers and emails for a single record

**Comment by lwhiteley** [comment]
ill look into selecting multiple contacts in one Intent, doesn't sound too far fetched

**Comment by rhaker** [comment]
it was different. I realized it as soon as closing. sorry.

I don't think this is an easy implementation. My guess is it's best handled via javascript, where you display an interface for each selection and inform the user to hit a button when they are done.

**Comment by rhaker** [comment]
@lwhiteley has now built out the multi select feature. Please see https://github.com/lwhiteley/react-native-android-contactpicker
